---
# ROLE: first_deploy
# roles/first_deploy/tasks/main.yml
#
# Runs the first Capistrano managed deployment
# Usage:
#    - { role: first_deploy, project_name: *required*, project_owner: *required*, project_version: *required* }
#
# Does a minimal install of a codebase from development mode to bootstrap a capistrano deployment
# The codebase being deployed must be capified and have a config/deploy/localhost.rb stage file
- name: remove previous known_hosts file
  file:
    path: /home/{{ ansible_ssh_user }}/.ssh/known_hosts
    state: absent

- name: generate rails secret
  command: openssl rand -hex 64
  register: rails_secret

- name: create shared config files
  become: yes
  template: src={{ item }}.j2 dest=/opt/{{ project_name }}/shared/config/{{ item }} owner=deploy group=deploy backup=no
  with_items:
      - database.yml
      - secrets.yml

- name: remove any previously checked out git branch
  become: yes
  file:
    path: /home/{{ ansible_ssh_user }}/{{ project_name }}
    state: absent

- name: clone repo
  git:
      repo: https://github.com/{{ project_owner }}/{{ project_name }}.git
      dest: /home/{{ ansible_ssh_user }}/{{ project_name }}
      version: "{{ project_version }}"

- name: install gems (bundle install)
  shell: bundle install
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ project_name }}

  # Set up a keypair so the ansible user can connect as the capistrano deploy user
- name: create deployment keypair for connection user
  user:
      name: "{{ ansible_ssh_user }}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa

- name: read public key
  slurp:
      src: /home/{{ ansible_ssh_user }}/.ssh/id_rsa.pub
  register: public_key

- name: add public key to deploy user
  become: yes
  authorized_key:
      user: deploy
      key: "{{ public_key.content | b64decode }}"

- name: create apache vhosts file
  become: yes
  template: src=apache_vhost.j2 dest=/etc/apache2/sites-enabled/{{ project_name }}.conf owner=root group=root backup=no

- name: restart apache to load new virtual host
  become: yes
  service: name=apache2 state=restarted

- name: remove managed schema
  become: yes
  file:
    path: /var/solr/data/{{ project_name }}/conf/managed_schema
    state: absent

- name: temporary symlink schema from git checkout to solr
  become: yes
  file: src=/home/{{ ansible_ssh_user }}/{{ project_name }}/solr/config/schema.xml dest=/var/solr/data/{{ project_name }}/conf/schema.xml state=link force=yes

- name: temporary symlink solrconfig from git checkout to solr
  become: yes
  file: src=/home/{{ ansible_ssh_user }}/{{ project_name }}/solr/config/solrconfig.xml dest=/var/solr/data/{{ project_name }}/conf/solrconfig.xml state=link force=yes

- name: restart solr
  become: true
  service: name=solr state=restarted

- stat: path="/home/{{ ansible_ssh_user }}/{{ project_name }}/config/{{ item }}"
  with_items:
    - 'analytics.yml'
    - 'blacklight.yml'
    - 'browse_everything_providers.yml'
    - 'fedora.yml'
    - 'solr.yml'
  register: st

- name: copy config files
  copy:
    src: "{{ item.stat.path }}"
    dest: '/opt/{{ project_name }}/shared/config/{{ item.item }}'
    remote_src: yes
    owner: deploy
    group: deploy
    mode: 0644
  with_items: "{{ st.results }}"
  when: item.stat.exists
  become: yes

- name: deploy to production directories with capistrano
  shell: cap -p --trace=stdout {{ cap_deployment }} deploy
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ project_name }}
  environment:
    PROJECT_OWNER: "{{ project_owner }}"
    PROJECT_NAME: "{{ project_name }}"
    BRANCH: "{{ project_version }}"

- name: symlink schema from code to solr
  become: yes
  file: src=/opt/{{ project_name }}/current/solr/config/schema.xml dest=/var/solr/data/{{ project_name }}/conf/schema.xml state=link force=yes

- name: symlink solrconfig from code to solr
  become: yes
  file: src=/opt/{{ project_name }}/current/solr/config/solrconfig.xml dest=/var/solr/data/{{ project_name }}/conf/solrconfig.xml state=link force=yes

- name: restart solr
  become: true
  service: name=solr state=restarted

- name: restart apache to load newly configured passenger application
  become: yes
  service: name=apache2 state=restarted

- name: ensure default admin set with rake
  become: yes
  become_user: deploy
  shell: RAILS_ENV=production bundle exec rake hyrax:default_admin_set:create
  args:
    chdir: /opt/{{ project_name }}/current
